#!/bin/bash

DAEMON_PATH="/usr/bin/"

DAEMON=manifold-xmlrpc
DAEMONOPTS=""

NAME=manifold
DESC="Manifold xml-rpc daemon"
PIDFILE=/var/run/$DAEMON.pid
PIDLOCKFILE=/var/run/$DAEMON.pid.lock
SCRIPTNAME=/etc/init.d/$NAME

case "$1" in
    start)
        printf "%-50s" "Starting $NAME..."
        cd $DAEMON_PATH
        PID=$($DAEMON $DAEMONOPTS >> /var/log/manifold.log  2>&1 & echo $!)
        if [ -z $PID ]; then
            printf "%s\n" "Fail"
        else
            echo $PID > $PIDFILE
            printf "%s\n" "Ok"
        fi
	;;
    status)
        printf "%-50s" "Checking $NAME..."
        if [ -f $PIDFILE ]; then
            PID=$(cat $PIDFILE)
            ps "$PID" >& /dev/null && printf "Running [$PID]\n" || printf "Process dead but pidfile exists\n"
        else
            printf "%s\n" "Service not running"
        fi
	;;
    stop)
        printf "%-50s" "Stopping $NAME"
        PID=`cat $PIDFILE`
        cd $DAEMON_PATH
        if [ -f $PIDFILE ]; then
            kill -HUP $PID
            printf "%s\n" "Ok"
            rm -f $PIDFILE
            rm -f $PIDLOCKFILE
        else
            printf "%s\n" "pidfile not found"
        fi
	;;
    restart)
        $0 stop
        $0 start
	;;
    *)
        echo "Usage: $0 {status|start|stop|restart}"
        exit 1
esac
